### ISSUE TITLE
Status page needs description/context

### ISSUE THREAD

**Issue by ghost** [ampproject/amp-status#1]
Landing on https://status.ampproject.org/ I'm unsure for what AMP the page is reporting a status of - all AMP pages are serving correctly, the status of the AMP Caches, the status of the AMP JS library, AMP ecosystem pages, the builds, etc.  I suggest including information that gives context of this page and what it is actually monitoring.  Something similar to what https://status.github.com has.

**Comment by danielrozenberg** [comment]
This page reports all of the above - if something isn't working in any of these parts of AMP, we can update this page arbitrarily. If you have a copy in mind put it here and I can add it to the main page

**Comment by ghost** [comment]
Include this:

This page provides the status of AMP serving and all its related services. If there are any interruptions, a note will be posted here.
